### PR TITLE
Failed compilation for zig0.14.0

### LINKED ISSUE #92: Failed compilation for zig0.14.0
Compilation for windows (zig-windows-x86_64-**0.14.0**-dev.544+7aaebd177) failed
+- run test
   +- zig test Debug native 1 errors
network.zig:1263:30: error: 
- struct **'os.windows.ws2_32.AI'** 
- has no member named **'NUMERICSERV'**

For previous version - zig-windows-x86_64-**0.13.0**.zip - it's ok

As proof of the life - please assign it to me

Thank you for code

### PR DESCRIPTION
**Pull request by g41797**
this pr fixes #92 

- fixed compilation for zig0.14.0 (actually for linux - zig-linux-x86_64-**0.14.0-dev**.1694+3b465ebec)
- unmaintained *goto-bus-stop/setup-zig* was replaced with **mlugg/setup-zig**

### CODE REVIEW

File: testsuite.zig [hunk 1]
```diff
@@ -15,11 +15,13 @@ test "Get endpoint list" {
     }
 }
 
+const host = "tcpbin.com";
```
Comment (ikskuh) [inline testsuite.zig:18]: Can you move this variable into the test and rename it `test_host`? It does not belong into the global namespace.

Comment (g41797) [reply testsuite.zig]: [done](https://github.com/ikskuh/zig-network/pull/93/commits/b66001d3c55046f7c1449ff5e1f28fcee6546d54)
